services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.11
    build:
      context: ./requirements/mariadb
    env_file:
      - ./requirements/.env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    container_name: wordpress
    image: wordpress:6.5
    build:
      context: ./requirements/wordpress
    env_file:
      - ./requirements/.env
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: always

  nginx:
    container_name: nginx
    image: nginx:1.25
    build:
      context: ./requirements/nginx
    env_file:
      - ./requirements/.env
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html:ro
    ports:
      - "443:443"
    networks:
      - inception
    restart: always

volumes:
  mariadb_data:
      driver: local
      driver_opts:
        type: none
        device: /home/dida/data/mariadb
        o: bind
  wordpress_data:
      driver: local
      driver_opts:
        type: none
        device: /home/dida/data/wordpress
        o: bind

networks:
  inception:
    driver: bridge
